# Event search, as on staging. Uses the OpenSearch of tmail_app.
opensearch.masterHost=opensearch
opensearch.port=9200
opensearch.hostScheme=http
opensearch.nb.shards=1
opensearch.nb.replica=0

opensearch.index.calendar.events.name=calendar-events
opensearch.alias.read.calendar.events.name=calendar-events-read
opensearch.alias.write.calendar.events.name=calendar-events-write
opensearch.index.calendar.events.max.ngram.diff=4
opensearch.index.calendar.events.min.ngram=3
