CREATE USER twake PASSWORD 'twake!1';
CREATE DATABASE fed TEMPLATE='template0' LOCALE='C' ENCODING='UTF8' OWNER='twake';
CREATE DATABASE tom TEMPLATE='template0' LOCALE='C' ENCODING='UTF8' OWNER='twake';
GRANT ALL PRIVILEGES ON DATABASE fed TO twake;
GRANT ALL PRIVILEGES ON DATABASE tom TO twake;
