
services:

  reverse-proxy:
    image: traefik:v2.6
    container_name: twake_reverse-proxy
    restart: unless-stopped
    ports:
      - 443:443

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.twake.local`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

    volumes:
      - ./traefik/config:/etc/traefik
      - ./traefik/ssl/:/ssl/
  twake-docker-socket:
    container_name: twake_docker-socket
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=1
  couchdb:
    image: couchdb:latest
    container_name: cozy-couchdb
    restart: unless-stopped
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      COUCHDB_HOST: cozy-couchdb
    volumes:
      - ./volumes/couchdb:/opt/couchdb/data

  cozy-stack:
    image: cozy/cozy-stack:latest
    container_name: cozy
    restart: unless-stopped
    depends_on:
      - couchdb
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cozy.rule=HostRegexp(`{subdomain:dwho-home|dwho|oauthcallback|ik|ik-home}.twake.local`)"
      - "traefik.http.routers.cozy.entrypoints=websecure"
      - "traefik.http.routers.cozy.tls=true"
      - "traefik.http.services.cozy.loadbalancer.server.port=8080"
    environment:
      COUCHDB_HOST: cozy-couchdb
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    extra_hosts:
      - "auth.twake.local:10.180.130.238"
    volumes:
      - ./volumes/cozy-stack/data:/var/lib/cozy/data
      - ./config:/etc/cozy
      
  lemonldap:
    image: yadd/lemonldap-ng-full:2.21.2-3
    container_name: twake_lemonldap-ng
    environment:
      - SSODOMAIN=twake.local
      - LOGLEVEL=debug
      - PROTECTION=none
      - PORTAL=https://auth.twake.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lemonldap-auth.rule=Host(`auth.twake.local`)"  
      - "traefik.http.services.lemonldap.loadbalancer.server.port=80"
      - "traefik.http.routers.lemonldap-man.rule=Host(`manager.twake.local`)"    
